### ISSUE TITLE
FXEDIT PROBLEM

### ISSUE THREAD

**Issue by GQGARCIA** [izzyreal/mpc#100]
YOU PRESS IT AND IT DOES NOT OPEN

**Comment by izzyreal** [comment]
The EB16 FX board is currently not emulated. What's the reason you want to access FXEDIT?

**Comment by GQGARCIA** [comment]
I USE IT FOR THE REVERB THAT IS THE SAME AS ( Lexicon MPX100) AND THE DISTORTION  FOR LOFI.

**Comment by izzyreal** [comment]
Closing this ticket because there's no plan to add EB16 emulation, because of the amount of work involved.

The only workaround I can think of is to use VMPC2000XL's Direct-to-disk Recorder screen (Shift + \) in combination with the MIXER screen's individual outs to directly write up to 5 stereo WAV files of your sequences, songs, etc. Then you can further process the WAVs in a DAW.
