### ISSUE TITLE
Attack and Decay

### ISSUE THREAD

**Issue by carlosnavarro938** [izzyreal/mpc#108]
Hello, 

Many thanks for sharing VMPC2000XL!

vMPC2000XL version: 0.3.1 VST3

Given a pad, (with assigned sample) I don't know how can adjust attack and decay in a similar way as in a conventional virtual sampler or vst synth in such a way that the sample play as long as a I have that pad pressed  and once I release it, start to fade out as long as decay is set (supose the sample is long enough or looped). I've tried different setup in decay in PARAMS, using Dcy md: END or START but I can't get it working as I want. Is there anything else I can try?

Thanks in advance.

**Comment by izzyreal** [comment]
Hi @carlosnavarro938,

Thanks for reaching out!

Most VSTs have an ADSR envelope. The early MPCs have what is in VMPC2000XL and it can be a little unintuitive and limited. Let's look at your specific use case:

```
...the sample plays as long as I have that pad pressed, and once I release it, the sample starts to fade out as long as decay is set.
```

What you're actually looking for is the release stage in an ADSR envelope. The MPC2000XL cannot do what you want here, because it doesn't have such a release stage.

Let me know if that answers your question.
