### ISSUE TITLE
Sampling within AUM as AUv3

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#153]
Would it be possible to sample directly into VMPC2000XL by adding the AUv3 as effect in AUM? Please see Koala sampler as an example where is can also be used as a instrument:

![image](https://user-images.githubusercontent.com/111270880/228607577-3ccd2e82-7af2-4495-a89c-1bfe6cb35e05.png)
![image](https://user-images.githubusercontent.com/111270880/228608089-579fe8c5-b69a-46fd-b576-92f108dc847e.png)

**Comment by izzyreal** [comment]
https://developer.apple.com/documentation/audiotoolbox/1584142-audio_unit_types

So far VMPC2000XL AUv3 was published as a [kAudioUnitType_MusicDevice](https://developer.apple.com/documentation/audiotoolbox/1584142-audio_unit_types/kaudiounittype_musicdevice).
From what I gather, this should give it MIDI in and audio out. Maybe also MIDI out... not sure if I ever tested this.

In the latest TestFlight it's published as a [kAudioUnitType_MusicEffect](https://developer.apple.com/documentation/audiotoolbox/1584142-audio_unit_types/kaudiounittype_musiceffect). From what I gather, this should give it audio in + out and MIDI in (but not out). I haven't tested it properly yet, but in AUM at least it shows up as an effect. When I put a synth before it, VMPC2000XL does not seem to pick up on the input, but I only ran a very quick test so far.

**Comment by messeraffe** [comment]
Indeed, it's the same for me. No audio input yet.

**Comment by messeraffe** [comment]
This is probably not related but I can’t see the VMPC2000XL folder under “on my iPad” anymore.  The standalone app does still show and load the samples though.

**Comment by izzyreal** [comment]
> This is probably not related but I can’t see the VMPC2000XL folder under “on my iPad” anymore. The standalone app does still show and load the samples though.

I just pushed another iOS version, can you try again?

**Comment by messeraffe** [comment]
Yes, the folder is back. Thank you

**Comment by izzyreal** [comment]
I figured out how to do it. In principle it's not that hard, but there are various conditions to mind when changing the `Info.plist` for Audio Units. For the sake of documentation and reference, let me repost what I [originally posted in The Audio Programmer Discord #juce channel](https://discord.com/channels/382895736356077570/1095858209773854731/1095914175210979378).

-----------------------------------
This is the hack https://github.com/izzyreal/JUCE/commit/fa1edd8465c3495a5ee4c9d8c34ce71d6cedb5be, 
and as far as I know adding this plist entry is the only thing that needs to happen. My plugin works well with just that change. I simply didn't notice it earlier because of all the Apple voodoo that works behind the scenes, probably AudioComponentRegistrar or something like that.

So I've summarized some things to keep in mind if someone decides to switch from single to multi `AudioComponents` entries, so your changes play nice with said voodoo. For me the below is reliable, so let me know if your experience is different.

A. `~/Library/Caches/AudioUnitCache` is not recreated after deleting it and running `auval`. As long as you don't start any other AU hosts, you don't have to be concerned about `AudioUnitCache`.

B. Clean your build folder and Derived Data folder every time you make changes to the `Info.plist` and create a new build.

C. Do the following 1. and 2. **before** running the binary artifact (the `.app`) of the build with a different `Info.plist` for your AppExtension:

1. Remove **all** previous builds and copies of your `.app` that contains the AUv3 `.appex` from your system, also from the **trash**. Think of IDE project build dirs, `/Applications` and so on.

2. `rm -rf ~/Library/Containers/nl.izmar.vmpc2000xl.vmpc2000xlAUv3`. Replace with your plugin bundle ID.

**Comment by izzyreal** [comment]
@messeraffe Keep your eyes peeled for a new iOS build 😄 Let me know how it goes.

**Comment by messeraffe** [comment]
Thanks @izzyreal 
Looks good. So far AUv3 only crashed twice. First time when I added VMPC as an effect for the first time and later while I was going crazy in the step editor :) Are you getting automated error reports for these as I did not get any opportunity to send something over.

**Comment by izzyreal** [comment]
Hmm maybe it crashed the first time because the `Info.plist` has changed.
I'll check out your Step Editor crash. I have one crash report from you on 13-4-2023. Indeed it comes with a downloadable full crash report like the ones you've been sending from macOS, so I think we're good there 👌

**Comment by messeraffe** [comment]
Short question: can we access the AUv3 saved files (PGM, ALL, SND etc.) in any way through the Files app and e.g. share it with the Mac to finalize the mix?

**Comment by izzyreal** [comment]
At the moment, no. I think we can use [this ticket](https://github.com/izzyreal/vmpc-juce/issues/40) for discussion. I'll write some ideas there.
