### ISSUE TITLE
VMPC2000XL macOS audio thread crashed out of the blue, 0x00000014 (no mapping for user instruction read)

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#164]
Attaching the crash reports here. 

Was just programming the drums on the standalone version and the app crashed when I changed the swing settings.

[20230407_crash.txt](https://github.com/izzyreal/mpc/files/11180066/20230407_crash.txt)

**Comment by izzyreal** [comment]
Odd 🤔 Nothing special is happening in the routine where the audiothread crashed.

According to https://github.com/bambulab/BambuStudio/issues/1572#issuecomment-1499915536 it can be related to multiple application installations. Since macOS does quite a bit of magic behind the scenes based on the presence of `.app` files, the only thing I can suggest right now is to remove all `VMPC2000XL.app` files on your system, remove them from your Trash as well, and reinstall VMPC2000XL.

Let me know if you indeed had multiple `.app` files on your system.

**Comment by messeraffe** [comment]
I just checked and at least in the `/Applications` folder I only have one `/VMPC2000XL.app`. Is there any other location I should look at as well?

**Comment by izzyreal** [comment]
Probably check with Spotlight (Cmd + Space) and type `VMPC2000XL.app`.

**Comment by izzyreal** [comment]
Do you regularly restart your Mac? If you're like me, you only restart it after updates. It may also help to do a restart.

**Comment by messeraffe** [comment]
> 

Yes, it´s only one instance

**Comment by izzyreal** [comment]
Optimistically closing this, assuming it didn't happen again.
