### ISSUE TITLE
16 level tuning

### ISSUE THREAD

**Issue by jaybaby0713** [izzyreal/mpc#243]
I wanted to know how to 16 levels tune a sound not velocity but the tuning (tuner)

**Comment by izzyreal** [comment]
See p.22, section named "The 16 LEVELS key" of https://www.platinumaudiolab.com/free_stuff/manuals/Akai/akai_mpc2000xl_manual.pdf

**Comment by jaybaby0713** [comment]
OK will this tell me how to 16 level tune?...and when i press erase will it just erase the pad a hit or the whole 16 level pad

**Comment by jaybaby0713** [comment]
I got it thanks sir...its the minus and plus buttons to get it to go to tuning

**Comment by jaybaby0713** [comment]
But the erase thing I still need to know does ot erase all buttons in the 16 level or just that one pad

**Comment by izzyreal** [comment]
> But the erase thing I still need to know does ot erase all buttons in the 16 level or just that one pad

I just checked on the original: if 16 LEVELS is still enabled, pressing any of the pads will erase any of the notes you just recorded with 16 LEVELS enabled.

I also tried it in VMPC2000XL, and the behaviour is the same there.

**Comment by izzyreal** [comment]
To be sure; when you use erase with 16 LEVELS disabled, the behaviour is as usual -- only the pads you press will be removed. Since recording in 16 LEVELS mode results in recording the same pad (but with different note variation values), to erase the events recorded under 16 LEVELS mode, you need to press the original pad you selected in this screen:
<img width="388" alt="image" src="https://github.com/user-attachments/assets/d5e2613f-cbd4-4ba6-a462-408b8f216fda">

**Comment by jaybaby0713** [comment]
Good stuff sir thanks alot

**Comment by izzyreal** [comment]
> Good stuff sir thanks alot

Wicked! You're welcome!
